version: '3.8'  # Spécifie la version de Docker Compose utilisée.

services:
  symfony:  # Définition du service Symfony, l'application principale.
    build:  # Construit l'image Docker à partir d'un Dockerfile.
      context: .  # Répertoire de contexte de build, ici le répertoire courant.
      dockerfile: .devcontainer/Dockerfile  # Chemin vers le Dockerfile utilisé pour le build.
    volumes:
      - .:/var/www/html  # Montage du code source dans le conteneur.
    ports:
      - "8080:80"  # Redirection du port 80 du conteneur vers le port 8080 de l'hôte.
    depends_on:
      - db  # Dépendance vers le service de base de données.
      - redis  # Dépendance vers le service Redis.

  db:  # Service de base de données MariaDB.
    image: mariadb:latest  # Utilise la dernière image MariaDB.
    environment:
      MYSQL_ROOT_PASSWORD: root  # Mot de passe root (à changer pour plus de sécurité).
      MYSQL_DATABASE: symfony  # Nom de la base de données.
      MYSQL_USER: symfony  # Utilisateur de la base de données.
      MYSQL_PASSWORD: symfony  # Mot de passe de l'utilisateur (à changer pour plus de sécurité).
    ports:
      - "3306:3306"  # Exposition du port de la base de données.
    volumes:
      - db_data:/var/lib/mysql  # Volume persistant pour les données de la base de données.

  redis:
    image: redis:latest  # Utilise la dernière image Redis.
    ports:
      - "6379:6379"  # Exposition du port Redis.

volumes:
  db_data:  # Définition du volume pour la persistance des données MariaDB.




# Ne pas utiliser latest pour les images Docker : spécifiez des versions précises pour éviter des surprises lors des mises à jour des images qui pourraient introduire des incompatibilités ou des failles de sécurité.
# Changer les mots de passe par défaut : les valeurs comme MYSQL_ROOT_PASSWORD: root doivent être remplacées par des mots de passe forts et idéalement gérés via des secrets.
# Ne pas exposer inutilement les ports : si le service n'est pas destiné à être accessible de l'extérieur, ne pas publier les ports sur l'hôte. Si nécessaire, assurez-vous que l'accès est sécurisé.
